version: '2'
services:
    jhipstersampleoauth2gateway-mongodb:
        image: mongo:4.0.2
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/JHipsterSampleOauth2Gateway/mongodb/:/data/db/
